# Archivo makefile simple

all: muestreo

procesamiento.o: procesamiento.c
	gcc -c procesamiento.c -Wall

archivos.o: archivo.c
	gcc -c archivos.c -Wall

muestreo.o: muestreo.c
	gcc -c muestreo.c -Wall


